// Edited state

// const jsonHook = ([
//     {"BaseDatos":"Sinco","modulo":1,"submodulo":"Configuracion","AddonNo":-137,"AddonNombre":"Encuestas de configuración ADPRO","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.Menus","Valor":"9634","ObsDet":"ADPRO/Mantenimiento/CONFIGURACION/Encuestas de configuración >> Valor recomendado:1 | Valor Actual:(1)","Colornivel1":"GREEN","Colornivel3":"GREEN","HorasBdAdicional":0.00,"SubModulo":"Configuracion","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
//     {"BaseDatos":"Sinco","modulo":1,"submodulo":"Almacén","AddonNo":-136,"AddonNombre":"Discriminación de insumos en la OC según fecha de requerimiento.","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"se cambia el valor del config CompPedFechaRq","ObsDet":"Fecha de requisición por detalle en las ordenes de compra, (Permite repetir el insumo en los detalles de la OC con fechas diferentes de requisición) (1=Premite; 0=Bloquea) >> Valor recomendado:1 | Valor Actual:(0)","Colornivel1":"RED","Colornivel3":"RED","HorasBdAdicional":0.00,"SubModulo":"Almacén","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
//     {"BaseDatos":"Sinco","modulo":1,"submodulo":"Almacén","AddonNo":-135,"AddonNombre":"Observaciones por insumo en el formato de impresión de OC","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"se cambia el valor del config Obsxdetalle_OC","ObsDet":"Habilita columna de obs x detalle en la 0C (SI=1 NO=0) aplica nueva version  >> Valor recomendado:1 | Valor Actual:(2)","Colornivel1":"RED","Colornivel3":"RED","HorasBdAdicional":0.00,"SubModulo":"Almacén","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
//     {"BaseDatos":"Sinco","modulo":1,"submodulo":"Compras","AddonNo":-134,"AddonNombre":"Migración de datos iniciales: agrupaciones, tipos de insumo y unidades de medida.","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"se cambia el valor del config ImportMaestros","ObsDet":"Habilita importación Unidad, Tipo , Agrupación Insumos 1:(SI), 0:(NO) >> Valor recomendado:1 | Valor Actual:(1)","Colornivel1":"GREEN","Colornivel3":"GREEN","HorasBdAdicional":0.00,"SubModulo":"Compras","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
//     {"BaseDatos":"Sinco","modulo":1,"submodulo":"Contratos","AddonNo":-130,"AddonNombre":"Otrosíes parametrizables impresión contrato civil.","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"se cambia el valor del config Con_MinutaOtroSi","ObsDet":"Activa funcionalidad de minuta para OtroSí 1:SI;0:No >> Valor recomendado:1 | Valor Actual:(0)","Colornivel1":"RED","Colornivel3":"RED","HorasBdAdicional":0.00,"SubModulo":"Contratos","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]}])

// export {jsonHook}

// Original State

// const jsonHook = ([
// {"BaseDatos":"Sinco","modulo":1,"submodulo":"Configuracion","AddonNo":-137,"AddonNombre":"<label>Encuestas de configuración ADPRO</label>","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.Menus","Valor":"9634","ObsDet":"ADPRO/Mantenimiento/CONFIGURACION/Encuestas de configuración >> Valor recomendado:1 | Valor Actual:(1)","Colornivel1":"GREEN","Colornivel3":"GREEN","HorasBdAdicional":0.00,"SubModulo":"Configuracion","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
// {"BaseDatos":"Sinco","modulo":1,"submodulo":"Almacén","AddonNo":-136,"AddonNombre":"<label>Discriminación de insumos en la OC según fecha de requerimiento.</label>","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"<i title=\"se cambia el valor del config\" style=\"margin-right:5px\" class=\"fa fa-anchor\" aria-hidden=\"true\"></i>CompPedFechaRq","ObsDet":"Fecha de requisición por detalle en las ordenes de compra, (Permite repetir el insumo en los detalles de la OC con fechas diferentes de requisición) (1=Premite; 0=Bloquea) >> Valor recomendado:1 | Valor Actual:(0)","Colornivel1":"RED","Colornivel3":"RED","HorasBdAdicional":0.00,"SubModulo":"Almacén","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
// {"BaseDatos":"Sinco","modulo":1,"submodulo":"Almacén","AddonNo":-135,"AddonNombre":"<label>Observaciones por insumo en el formato de impresión de OC</label>","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"<i title=\"se cambia el valor del config\" style=\"margin-right:5px\" class=\"fa fa-anchor\" aria-hidden=\"true\"></i>Obsxdetalle_OC","ObsDet":"Habilita columna de obs x detalle en la 0C (SI=1 NO=0) aplica nueva version  >> Valor recomendado:1 | Valor Actual:(2)","Colornivel1":"RED","Colornivel3":"RED","HorasBdAdicional":0.00,"SubModulo":"Almacén","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
// {"BaseDatos":"Sinco","modulo":1,"submodulo":"Compras","AddonNo":-134,"AddonNombre":"<label>Migración de datos iniciales: agrupaciones, tipos de insumo y unidades de medida.</label>","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"<i title=\"se cambia el valor del config\" style=\"margin-right:5px\" class=\"fa fa-anchor\" aria-hidden=\"true\"></i>ImportMaestros","ObsDet":"Habilita importación Unidad, Tipo , Agrupación Insumos 1:(SI), 0:(NO) >> Valor recomendado:1 | Valor Actual:(1)","Colornivel1":"GREEN","Colornivel3":"GREEN","HorasBdAdicional":0.00,"SubModulo":"Compras","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]},
// {"BaseDatos":"Sinco","modulo":1,"submodulo":"Contratos","AddonNo":-130,"AddonNombre":"<label>Otrosíes parametrizables impresión contrato civil.</label>","HorasInstalacion":0,"costo":"$ 0.00","Obs":"","Tabla":"dbo.ADPConfig","Valor":"<i title=\"se cambia el valor del config\" style=\"margin-right:5px\" class=\"fa fa-anchor\" aria-hidden=\"true\"></i>Con_MinutaOtroSi","ObsDet":"Activa funcionalidad de minuta para OtroSí 1:SI;0:No >> Valor recomendado:1 | Valor Actual:(0)","Colornivel1":"RED","Colornivel3":"RED","HorasBdAdicional":0.00,"SubModulo":"Contratos","FechaPublicacion":"","RutaPDF":"","Requisitos":"","Obsoleto":false,"Reemplazo":"","auditoria":[]}
// ])

import { useState, useContext, createContext } from "react";

const addonsContext = createContext();

export function useAddonsContext() {
    return useContext(addonsContext);
}

export function AddonsDataProvider(props) {
    const [addonsData, setAddonsData] = useState([
        { "BaseDatos": "Sinco", "modulo": 1, "submodulo": "Configuracion", "AddonNo": -137, "AddonNombre": "Encuestas de configuración ADPRO", "HorasInstalacion": 0, "costo": "$ 0.00", "Obs": "", "Tabla": "dbo.Menus", "Valor": "9634", "ObsDet": "ADPRO/Mantenimiento/CONFIGURACION/Encuestas de configuración >> Valor recomendado:1 | Valor Actual:(1)", "Colornivel1": "GREEN", "Colornivel3": "GREEN", "HorasBdAdicional": 0.00, "SubModulo": "Configuracion", "FechaPublicacion": "", "RutaPDF": "", "Requisitos": "", "Obsoleto": false, "Reemplazo": "", "auditoria": [] },
        { "BaseDatos": "Sinco", "modulo": 1, "submodulo": "Almacén", "AddonNo": -136, "AddonNombre": "Discriminación de insumos en la OC según fecha de requerimiento.", "HorasInstalacion": 0, "costo": "$ 0.00", "Obs": "", "Tabla": "dbo.ADPConfig", "Valor": "se cambia el valor del config CompPedFechaRq", "ObsDet": "Fecha de requisición por detalle en las ordenes de compra, (Permite repetir el insumo en los detalles de la OC con fechas diferentes de requisición) (1=Premite; 0=Bloquea) >> Valor recomendado:1 | Valor Actual:(0)", "Colornivel1": "RED", "Colornivel3": "RED", "HorasBdAdicional": 0.00, "SubModulo": "Almacén", "FechaPublicacion": "", "RutaPDF": "", "Requisitos": "", "Obsoleto": false, "Reemplazo": "", "auditoria": [] },
        { "BaseDatos": "Sinco", "modulo": 1, "submodulo": "Almacén", "AddonNo": -135, "AddonNombre": "Observaciones por insumo en el formato de impresión de OC", "HorasInstalacion": 0, "costo": "$ 0.00", "Obs": "", "Tabla": "dbo.ADPConfig", "Valor": "se cambia el valor del config Obsxdetalle_OC", "ObsDet": "Habilita columna de obs x detalle en la 0C (SI=1 NO=0) aplica nueva version  >> Valor recomendado:1 | Valor Actual:(2)", "Colornivel1": "RED", "Colornivel3": "RED", "HorasBdAdicional": 0.00, "SubModulo": "Almacén", "FechaPublicacion": "", "RutaPDF": "", "Requisitos": "", "Obsoleto": false, "Reemplazo": "", "auditoria": [] },
        { "BaseDatos": "Sinco", "modulo": 1, "submodulo": "Compras", "AddonNo": -134, "AddonNombre": "Migración de datos iniciales: agrupaciones, tipos de insumo y unidades de medida.", "HorasInstalacion": 0, "costo": "$ 0.00", "Obs": "", "Tabla": "dbo.ADPConfig", "Valor": "se cambia el valor del config ImportMaestros", "ObsDet": "Habilita importación Unidad, Tipo , Agrupación Insumos 1:(SI), 0:(NO) >> Valor recomendado:1 | Valor Actual:(1)", "Colornivel1": "GREEN", "Colornivel3": "GREEN", "HorasBdAdicional": 0.00, "SubModulo": "Compras", "FechaPublicacion": "", "RutaPDF": "", "Requisitos": "", "Obsoleto": false, "Reemplazo": "", "auditoria": [] },
        { "BaseDatos": "Sinco", "modulo": 1, "submodulo": "Contratos", "AddonNo": -130, "AddonNombre": "Otrosíes parametrizables impresión contrato civil.", "HorasInstalacion": 0, "costo": "$ 0.00", "Obs": "", "Tabla": "dbo.ADPConfig", "Valor": "se cambia el valor del config Con_MinutaOtroSi", "ObsDet": "Activa funcionalidad de minuta para OtroSí 1:SI;0:No >> Valor recomendado:1 | Valor Actual:(0)", "Colornivel1": "RED", "Colornivel3": "RED", "HorasBdAdicional": 0.00, "SubModulo": "Contratos", "FechaPublicacion": "", "RutaPDF": "", "Requisitos": "", "Obsoleto": false, "Reemplazo": "", "auditoria": [] }
    ])


    return (
        <addonsContext.Provider value={addonsData}>
            {props.children}
        </addonsContext.Provider>
    );
}